name: Sync Fork on Parent Push

on:
  repository_dispatch:
    types: [sync-trigger]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/nss-nitc/nss-website.git

      - name: Fetch and Merge Changes
        run: |
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
